In [87]:
import pandas as pd

In [88]:
records = pd.read_csv("Online_Learning_Data.csv")

In [89]:
records

,Month,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,Italy,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,2004-01,0,0,0,0,35,44,0,0,0,...,0,0,0,100,0,53,73,0,69,75
1,2004-02,100,0,0,43,38,59,41,0,0,...,100,31,0,0,82,0,72,0,50,56
2,2004-03,0,90,0,0,48,74,0,0,0,...,0,0,0,0,100,0,0,0,81,50
3,2004-04,0,0,0,0,39,72,39,0,56,...,0,0,0,85,0,0,57,0,38,74
4,2004-05,0,0,0,0,34,24,100,0,0,...,0,66,100,0,0,87,0,0,37,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2021-06,4,9,15,8,31,24,8,0,23,...,12,76,13,2,32,41,5,7,31,28
210,2021-07,5,6,15,8,44,21,7,1,18,...,6,35,8,0,26,22,5,7,29,26
211,2021-08,9,7,11,10,32,18,4,2,9,...,2,32,10,2,30,13,4,7,27,36
212,2021-09,5,6,15,6,47,17,8,0,19,...,4,63,3,2,29,11,3,7,38,32
213,2021-10,20,4,11,7,20,15,11,1,40,...,0,74,0,0,33,13,14,0,53,32

In [90]:
records.columns

Index(['Month', 'Argentina', 'Brazil', 'Colombia', 'France', 'Germany',
       'India', 'Indonesia', 'Iran', 'Italy', 'Mexico', 'Peru', 'Philippines',
       'Poland', 'Russia', 'South Africa', 'Spain', 'Turkey', 'Ukraine',
       'United Kingdom', 'United States of America'],
      dtype='object')

In [91]:
## record.duplicated

In [92]:
## insert a new column named "Year"

#position, column name, values

In [93]:
records.dtypes

Month                       object
Argentina                    int64
Brazil                       int64
Colombia                     int64
France                       int64
Germany                      int64
India                        int64
Indonesia                    int64
Iran                         int64
Italy                        int64
Mexico                       int64
Peru                         int64
Philippines                  int64
Poland                       int64
Russia                       int64
South Africa                 int64
Spain                        int64
Turkey                       int64
Ukraine                      int64
United Kingdom               int64
United States of America     int64
dtype: object

In [94]:
records['Month'].astype('datetime64[ns]')

0     2004-01-01
1     2004-02-01
2     2004-03-01
3     2004-04-01
4     2004-05-01
         ...
209   2021-06-01
210   2021-07-01
211   2021-08-01
212   2021-09-01
213   2021-10-01
Name: Month, Length: 214, dtype: datetime64[ns]

In [95]:
records['Month']=records['Month'].astype('datetime64[ns]')
records

,Month,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,Italy,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,2004-01-01,0,0,0,0,35,44,0,0,0,...,0,0,0,100,0,53,73,0,69,75
1,2004-02-01,100,0,0,43,38,59,41,0,0,...,100,31,0,0,82,0,72,0,50,56
2,2004-03-01,0,90,0,0,48,74,0,0,0,...,0,0,0,0,100,0,0,0,81,50
3,2004-04-01,0,0,0,0,39,72,39,0,56,...,0,0,0,85,0,0,57,0,38,74
4,2004-05-01,0,0,0,0,34,24,100,0,0,...,0,66,100,0,0,87,0,0,37,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2021-06-01,4,9,15,8,31,24,8,0,23,...,12,76,13,2,32,41,5,7,31,28
210,2021-07-01,5,6,15,8,44,21,7,1,18,...,6,35,8,0,26,22,5,7,29,26
211,2021-08-01,9,7,11,10,32,18,4,2,9,...,2,32,10,2,30,13,4,7,27,36
212,2021-09-01,5,6,15,6,47,17,8,0,19,...,4,63,3,2,29,11,3,7,38,32
213,2021-10-01,20,4,11,7,20,15,11,1,40,...,0,74,0,0,33,13,14,0,53,32

In [96]:
#to insert a new column before month , name the column year
records['Month'].dt.to_period('y')

0      2004
1      2004
2      2004
3      2004
4      2004
       ...
209    2021
210    2021
211    2021
212    2021
213    2021
Name: Month, Length: 214, dtype: period[A-DEC]

In [97]:
records

,Month,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,Italy,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,2004-01-01,0,0,0,0,35,44,0,0,0,...,0,0,0,100,0,53,73,0,69,75
1,2004-02-01,100,0,0,43,38,59,41,0,0,...,100,31,0,0,82,0,72,0,50,56
2,2004-03-01,0,90,0,0,48,74,0,0,0,...,0,0,0,0,100,0,0,0,81,50
3,2004-04-01,0,0,0,0,39,72,39,0,56,...,0,0,0,85,0,0,57,0,38,74
4,2004-05-01,0,0,0,0,34,24,100,0,0,...,0,66,100,0,0,87,0,0,37,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2021-06-01,4,9,15,8,31,24,8,0,23,...,12,76,13,2,32,41,5,7,31,28
210,2021-07-01,5,6,15,8,44,21,7,1,18,...,6,35,8,0,26,22,5,7,29,26
211,2021-08-01,9,7,11,10,32,18,4,2,9,...,2,32,10,2,30,13,4,7,27,36
212,2021-09-01,5,6,15,6,47,17,8,0,19,...,4,63,3,2,29,11,3,7,38,32
213,2021-10-01,20,4,11,7,20,15,11,1,40,...,0,74,0,0,33,13,14,0,53,32

In [98]:
records.insert(0,"Year","")

In [99]:
records

,Year,Month,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,,2004-01-01,0,0,0,0,35,44,0,0,...,0,0,0,100,0,53,73,0,69,75
1,,2004-02-01,100,0,0,43,38,59,41,0,...,100,31,0,0,82,0,72,0,50,56
2,,2004-03-01,0,90,0,0,48,74,0,0,...,0,0,0,0,100,0,0,0,81,50
3,,2004-04-01,0,0,0,0,39,72,39,0,...,0,0,0,85,0,0,57,0,38,74
4,,2004-05-01,0,0,0,0,34,24,100,0,...,0,66,100,0,0,87,0,0,37,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,,2021-06-01,4,9,15,8,31,24,8,0,...,12,76,13,2,32,41,5,7,31,28
210,,2021-07-01,5,6,15,8,44,21,7,1,...,6,35,8,0,26,22,5,7,29,26
211,,2021-08-01,9,7,11,10,32,18,4,2,...,2,32,10,2,30,13,4,7,27,36
212,,2021-09-01,5,6,15,6,47,17,8,0,...,4,63,3,2,29,11,3,7,38,32
213,,2021-10-01,20,4,11,7,20,15,11,1,...,0,74,0,0,33,13,14,0,53,32

In [100]:
records["Year"]=records['Month'].dt.to_period('y')

In [101]:
records

,Year,Month,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,2004,2004-01-01,0,0,0,0,35,44,0,0,...,0,0,0,100,0,53,73,0,69,75
1,2004,2004-02-01,100,0,0,43,38,59,41,0,...,100,31,0,0,82,0,72,0,50,56
2,2004,2004-03-01,0,90,0,0,48,74,0,0,...,0,0,0,0,100,0,0,0,81,50
3,2004,2004-04-01,0,0,0,0,39,72,39,0,...,0,0,0,85,0,0,57,0,38,74
4,2004,2004-05-01,0,0,0,0,34,24,100,0,...,0,66,100,0,0,87,0,0,37,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,2021,2021-06-01,4,9,15,8,31,24,8,0,...,12,76,13,2,32,41,5,7,31,28
210,2021,2021-07-01,5,6,15,8,44,21,7,1,...,6,35,8,0,26,22,5,7,29,26
211,2021,2021-08-01,9,7,11,10,32,18,4,2,...,2,32,10,2,30,13,4,7,27,36
212,2021,2021-09-01,5,6,15,6,47,17,8,0,...,4,63,3,2,29,11,3,7,38,32
213,2021,2021-10-01,20,4,11,7,20,15,11,1,...,0,74,0,0,33,13,14,0,53,32

In [102]:
records['Year'].unique()

<PeriodArray>
['2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
 '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
Length: 18, dtype: period[A-DEC]

In [103]:
records.groupby('Year').sum(numeric_only="True").reset_index()

,Year,Argentina,Brazil,Colombia,France,Germany,India,Indonesia,Iran,Italy,...,Peru,Philippines,Poland,Russia,South Africa,Spain,Turkey,Ukraine,United Kingdom,United States of America
0,2004,100,190,0,235,585,529,250,66,247,...,100,222,200,251,367,275,382,0,705,747
1,2005,38,63,178,126,455,797,140,232,141,...,38,150,362,180,112,374,161,0,547,723
2,2006,73,63,0,183,515,636,81,121,292,...,40,136,230,33,162,140,88,0,513,665
3,2007,85,110,96,166,550,527,94,177,272,...,87,107,316,57,125,182,75,100,487,715
4,2008,35,98,107,109,607,461,41,169,154,...,0,146,86,10,154,270,47,109,459,687
5,2009,18,95,59,132,490,449,68,154,124,...,19,108,149,24,129,266,47,110,471,750
6,2010,37,60,45,98,508,365,51,91,138,...,74,95,192,19,200,261,34,35,461,725
7,2011,33,89,54,118,346,313,25,94,111,...,26,66,182,12,136,258,27,70,474,674
8,2012,32,68,109,92,431,284,29,96,160,...,34,68,154,17,154,405,30,68,493,631
9,2013,33,74,103,91,381,278,21,71,156,...,28,63,139,7,160,485,33,84,492,649
10,2014,27,86,76,78,490,254,18,45,178,...,37,58,163,6,167,352,34,55,460,615
11,2015,35,83,47,91,404,261,20,48,187,...,29,53,162,11,120,345,37,43,431,565
12,2016,27,179,66,112,448,188,14,29,296,...,22,65,184,12,112,333,31,62,387,411
13,2017,20,140,39,97,542,176,12,21,209,...,53,70,145,10,167,226,36,44,374,398
14,2018,30,86,75,100,423,135,15,21,219,...,32,53,143,13,149,284,32,68,379,351
15,2019,26,80,91,126,458,139,18,12,203,...,29,56,142,19,196,319,28,77,368,328
16,2020,52,115,111,149,632,247,77,19,372,...,76,516,300,14,498,546,66,90,693,749
17,2021,63,79,109,79,450,181,77,8,216,...,58,702,131,14,286,233,61,65,468,315

In [104]:
records["Year"] = records["Year"].dt.to_timestamp()

In [108]:
a=records.groupby('Year').sum(numeric_only="True").reset_index()

In [106]:
import plotly.express as px

In [107]:
px.line(a, x="Year", y="Germany", title= "Line chart",text="Germany")